### ISSUE TITLE
[Etude] Improve ETL flow

### ISSUE THREAD

**Issue by celiacheff** [tchapgouv/tchap-stats#15]
## Problématiques
Ajouter des transformations 
Rendre générique et lisibles les scripts afin de simplifier la maintenance
Simplifier et automatiser la création de nouvelles stats
Contraintes: 
- performance
- la prise en main par un ops et un dev

#### Exemples de transformation
- Ajout du parsing des Users Agent
- Création automatiques des tables sur Metabase à partir d'un export CSV et d'un fichier de config
- Refactoring des scripts avec un nouveau language

#### Choix du language
- Bash (actuel)
- Perl (bon choix mais peu maîtrisé par les devs)
- Python (semble le choix de consensus)

#### Stratégie de scripting
- Simple (actuel)
- Outil ETL déjà dispo à étudier
- Solution maison

#### Strategie de source de données
- Fetch CSV via S3 (actuel)
- Mise en place d'un replica hors MI (avantage: schema de données inclus, transfo en PS ou embed Python)

**Comment by celiacheff** [comment]
Ma recherche personnelle
Au niveau des outils existants en Python, [petl](https://pypi.org/project/petl/) me semble un bon compromis simplicité/efficacité.
J'ai également jeté un oeil sur [Bonobo](https://github.com/python-bonobo) que je trouve un peu complexe en comparaison.

**Comment by odelcroi** [comment]
## Améliorations du systeme en place

- utiliser les replica plutôt que d'attaquer les bases transactionnelles (ie : utilisées par le backend)
- évaluer le role des Materialized View et Foreign Table dans les problèmes de performance rencontrés

## Proposition d'une solution ETL

`BDD REPLICA (home server) ---(workflow 1)---> S3 [csv] ----(worflow 2)----> Metabase
`

(1) le workflow d'extraction et d'aggregation des données devrait : 
- utiliser les replicas et pas les bases transactionnelles
- produire des petits csv par jour et par table contenant les données correspondantes
- ne pas produire de csv si un des home server ne répond pas
- être idempotent : si on execute plusieurs fois les scripts, ils doivent produire le même résultat
si on execute plusieurs fois les scripts, ils doivent produire le même résultat
- il pourrait éviter d'utiliser des mécanismes de Materialized View et Foreign Table
- un admin devrait pouvoir voir facilement quels csv ont été produits
- un admin devrait pouvoir lancer un script manuellement
- être testé facilement sur un environnement de dev

(2) le workflow de Load dans Metabase depuis S3 devrait
- importer les fichiers csv si il n'ont pas déjà été importé
- être idempotent : si on execute plusieurs fois les scripts, ils doivent écraser les données dans metabase (pas d'incréments)
- un administrateur devrait pouvoir voir facilement quels csv ont été importés
- un administrateur devrait pouvoir lancer les scripts d'import facilement

Le système complet pourrait être rendu open source afin d''être réutilisé par d'autres projets. Une sorte de Synapse Log extractor.
