### ISSUE TITLE
Quelles sont les heures de pointe d'utilisation par home server?

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-stats#22]
A quelle heure les membres de Tchap echangent ils le plus de message? 

par home server

**Comment by jdauphant** [comment]
Tu peux calculer cette donnée dans metabase

**Comment by odelcroi** [comment]
done : 
<img width="698" alt="image" src="https://github.com/tchapgouv/tchap-stats/assets/4077729/61306596-1396-49d7-8e86-c2fecb570de6">

https://stats.tchap.incubateur.net/public/dashboard/b5c5d23d-b5c5-4d21-a2d8-765fa2864f13?instance=
