### ISSUE TITLE
user_monthly_visits isn't refresh automaticaly

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-stats#24]
The command "REFRESH MATERIALIZED VIEW CONCURRENTLY user_monthly_visits;" isn't run at each import.

This don't run : 
https://github.com/tchapgouv/tchap-stats/blob/f2ca32d88226d99c1fd1f2ea5d96540b2ef93f11/scripts/insert_user_daily_visits_data.sql#L12

**Comment by odelcroi** [comment]
user_monthly_visits is deprecated, use https://github.com/tchapgouv/tchap-stats/wiki/Visites-Quotidiennes-des-Utilisateurs-par-Mois-sur-1-An-(%60user_daily_visits_by_month_1y%60) instead
