### ISSUE TITLE
[prod] stats - pourquoi le nombre de message baisse?

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-stats#59]
En lien avec https://github.com/tchapgouv/tchap-infra/issues/2573
Service : Synapse, Stats

**Describe the bug**
Les messages encrypted sont en chute libre

<img width="469" alt="image" src="https://github.com/tchapgouv/tchap-infra/assets/4077729/bc2a1eda-affc-4144-848d-fcc6a7b01e05">

**To Reproduce**
Vérifier que les data de "message encrypted" sont bien exporté/importé 

side effect or cause : 
L'événement de création de salon est "cassé"

<img width="486" alt="image" src="https://github.com/tchapgouv/tchap-infra/assets/4077729/9efdd1e0-e27e-40ad-ae49-39dfaff31f7d">

**Comment by odelcroi** [comment]
Comparatif des messages echanges des plus domaines entre [avril 2023](https://stats.tchap.incubateur.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjcsImFnZ3JlZ2F0aW9uIjpbWyJzdW0iLFsiZmllbGQiLDQ5LHsiYmFzZS10eXBlIjoidHlwZS9JbnRlZ2VyIn1dXV0sImJyZWFrb3V0IjpbWyJmaWVsZCIsNDcseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV1dLCJmaWx0ZXIiOlsiYW5kIixbImJldHdlZW4iLFsiKyIsWyJmaWVsZCIsNDUsbnVsbF0sWyJpbnRlcnZhbCIsMTAsIm1vbnRoIl1dLFsicmVsYXRpdmUtZGF0ZXRpbWUiLC0xLCJtb250aCJdLFsicmVsYXRpdmUtZGF0ZXRpbWUiLDAsIm1vbnRoIl1dLFsiPSIsWyJmaWVsZCIsNDYsbnVsbF0sIm0ucm9vbS5tZXNzYWdlIiwibS5yb29tLmVuY3J5cHRlZCJdXSwib3JkZXItYnkiOltbImRlc2MiLFsiYWdncmVnYXRpb24iLDBdXV19fSwiZGlzcGxheSI6ImJhciIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnsidGFibGUucGl2b3QiOmZhbHNlfSwib3JpZ2luYWxfY2FyZF9pZCI6bnVsbH0=)(a gauche) et [novembre 2023](https://stats.tchap.incubateur.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjcsImFnZ3JlZ2F0aW9uIjpbWyJzdW0iLFsiZmllbGQiLDQ5LHsiYmFzZS10eXBlIjoidHlwZS9JbnRlZ2VyIn1dXV0sImJyZWFrb3V0IjpbWyJmaWVsZCIsNDcseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV1dLCJmaWx0ZXIiOlsiYW5kIixbImJldHdlZW4iLFsiKyIsWyJmaWVsZCIsNDUsbnVsbF0sWyJpbnRlcnZhbCIsMywibW9udGgiXV0sWyJyZWxhdGl2ZS1kYXRldGltZSIsLTEsIm1vbnRoIl0sWyJyZWxhdGl2ZS1kYXRldGltZSIsMCwibW9udGgiXV0sWyI9IixbImZpZWxkIiw0NixudWxsXSwibS5yb29tLm1lc3NhZ2UiLCJtLnJvb20uZW5jcnlwdGVkIl1dLCJvcmRlci1ieSI6W1siZGVzYyIsWyJhZ2dyZWdhdGlvbiIsMF1dXX19LCJkaXNwbGF5IjoiYmFyIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJ0YWJsZS5waXZvdCI6ZmFsc2V9LCJvcmlnaW5hbF9jYXJkX2lkIjpudWxsfQ==)(a droite)

<img width="1244" alt="image" src="https://github.com/tchapgouv/tchap-infra/assets/3725676/5e3e7160-9748-46de-a213-effc28e6109a">

=> on peut voir qu'on a une baisse importante de 30%(a vu d'oeil)

**Comment by odelcroi** [comment]
![image](https://github.com/tchapgouv/tchap-infra/assets/4077729/068ad781-c22f-4577-b05c-d12b0c4d64d5)


https://stats.tchap.incubateur.net/public/dashboard/6789f7bc-163f-49bb-b703-797b6a0a4892

**Comment by odelcroi** [comment]
> La crypto v2 est activée sur iOS depuis juin 2023 et sur Android vers septembre 2023.
> C'est peut-être une piste.

Je n'ai pas d'idée sur comment avancer sur cette piste :/

**Comment by NicolasBuquet** [comment]
@odelcroi @julie-ri 
Après réflexion, l'activation de la crypto v2 a dû réduire les renvois de CLEFS, mais sans influence sur les envois de MESSAGES.

Par contre, il faut vérifier le workflow des datas qui servent à ces stats d'envois de messages : 
1. export des events de la base PostgreSQL vers metabase
    - y a-t-il eu une modification dans les données extraites
    - y a-t-il eu une modification dans la manière de consolider les données pour l'export vers Metabase
3. requête sur metabase pour sortir les stats
    - y a-t-il eu modification sur la requête

**Comment by jdauphant** [comment]
![image](https://github.com/tchapgouv/tchap-stats/assets/1238254/27d11617-89f7-436b-839a-1701e058d10c)
@odelcroi  Il y a une baisse d'ajout des membres dans les salons aussi.
Les room.create ont disparu à partir de mai 2023, avant l'ajout du SDK Crypto.

Vous avez vérifié les événements dans une des bases de prod pour voir si vous tombez sur les mêmes chiffres que metabase ?

**Comment by jdauphant** [comment]
Le 26 avril et 3 mail 2023, il y a eu le changement de room_level par défaut en prod : 
https://github.com/tchapgouv/tchap-infra/pull/1776
https://github.com/tchapgouv/tchap-infra/pull/1777
ça peut expliquer un changement de comportement sur les m.room.create et sur l'ajout de membre. (ça n'explique pas le baisse des messages par contre mais moins de salons c'est potenciellement moins de messages)

**Comment by jdauphant** [comment]
![image](https://github.com/tchapgouv/tchap-stats/assets/1238254/fed553a0-18e8-454c-992b-b9391986652c)
En ajoutant les messages à la courbe, le pic de message est en mars 2023 (c'était en croissance jusqu'à mars, puis ça part en décroissance sur les messages et le nombre d'ajout de membre dans les salons).

**Comment by odelcroi** [comment]
- l'évenement `m.room.member` correspond aux entrées et sorties d'un salon. L'activité décroit en effet depuis mars 2023
-> est ce que c'est sur toutes les instances?

**Comment by odelcroi** [comment]
effet de bord de : https://github.com/tchapgouv/tchap-infra/issues/2622

**Comment by odelcroi** [comment]
fixed by #64 
- delete events_aggregate table
- relaunch scripts to insert data from new export into the table events_aggregate

**Comment by odelcroi** [comment]
### Before
<img width="1257" alt="Capture d’écran 2024-05-06 à 11 15 40" src="https://github.com/tchapgouv/tchap-stats/assets/4077729/dee7e923-af32-4d55-88a7-8c857680f182">

### After
<img width="1100" alt="image" src="https://github.com/tchapgouv/tchap-stats/assets/4077729/71ab2f26-cc2b-489f-b016-ee6ab2bbf651">
