### ISSUE TITLE
stats -  combien de users ont rejoint leur room Tchap Info

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-stats#62]
Demande de tracking de la part des bizdev : 
- Combien de users ont rejoint leur room Tchap Info
- Combien de users ont quitté leur room Tchap Info
- Combien de users ont lu le dernier message

**Comment by MatMaul** [comment]
La room est en auto join donc le point 1 n'est pas utile.

Pour le point 3, à savoir aussi que ils vont recevoir une notif sur les mobiles, donc meme si on a pas le read receipt de lecture ils vont surement l'avoir lu :innocent:
